#!/bin/sh

first="$PWD"

files=`ls -lapH | sed 1d`
selection=`printf "%s\n%s" "$first" "$files" | cmenu -t 1`

case "$selection" in
	d*) isDir='yes';;
esac

target="`printf '%s' "$selection" | awk '{ print $9 }'`"

[ "$target" = "" ] && exec printf "%s" "$PWD";

[ "$isDir" = 'yes' ] && {
	cd $target || notify-send "cannot change dir!" ;
	exec dired $@
}

[ "$1" = "" ] && $TERMINAL -e opener "$target" 2>/dev/null 1>/dev/null &
[ "$1" = "-i" ] && opener "$target"
exec dired $@
