#!/bin/sh

first="$PWD"

files=`ls -lapH | sed 1d`
selection=`printf "%s\n%s" "$first" "$files" | cmenu -t 1`

case "$selection" in
	d*) isDir='yes';;
esac

target="`printf '%s' "$selection" | awk '{ print $9 }'`"

[ "$target" = "" ] && exec printf "%s" "$PWD";

[ "$isDir" = 'yes' ] && {
	cd $target || notify-send "cannot change dir!" ;
	exec dired
}

opener $target
exec dired
